/* test_kline.c - 0x052D multi-period K-lines.
 *
 * The three reply fixtures are the bytes a live public node returned; they cover
 * a daily series, an intraday series and an index series, which between them
 * exercise both date encodings and the optional breadth fields.  See
 * output/kline_probe_evidence.txt.
 *
 * The daily fixture is also the point where four independent sources agree:
 * the 20260612 bar decoded here reads open 16.79 / high 17.49 / low 16.73 /
 * close 17.39 / volume 16826060, and the same day's zst_cache image reports
 * 05=16.790000 06=17.490000 07=16.730000 08=17.390000 10=16826061. */
#include <stdio.h>
#include <string.h>

#include "tdx_kline.h"
#include "tdx_kline_json.h"

/* The three reply fixtures are the bytes a live public node returned.  They are
 * generated by output/make_kline_fixtures.py from output/kline_probe_evidence.txt
 * rather than pasted in by hand, so the test reads the server's actual stream.
 *
 * Between them they cover a daily series, an intraday series and an index series,
 * which exercises both date encodings and the optional breadth fields.
 *
 * The daily series is also where four independent sources agree: the 20260612 bar
 * reads open 16.79 / high 17.49 / low 16.73 / close 17.39 / volume 16826060, and
 * the same day's zst_cache image reports 05=16.790000 06=17.490000 07=16.730000
 * 08=17.390000 10=16826061. */
#include "kline_fixtures.h"

static int failures = 0;

#define CHECK(condition, ...)                                                        \
    do {                                                                             \
        if (!(condition)) {                                                          \
            printf("FAIL %s:%d: ", __FILE__, __LINE__);                              \
            printf(__VA_ARGS__);                                                     \
            printf("\n");                                                            \
            failures++;                                                              \
        }                                                                            \
    } while (0)

/* --- periods ---------------------------------------------------------- */

static void test_periods(void) {
    tdx_kline_period period;
    tdx_error error;
    error.message[0] = '\0';

    CHECK(tdx_kline_period_parse("day", &period, &error) == TDX_OK &&
              period.id == 4 && period.intraday == 0 && strcmp(period.name, "day") == 0,
          "day: %s", error.message);
    CHECK(tdx_kline_period_parse("week", &period, &error) == TDX_OK && period.id == 5 &&
              period.intraday == 0,
          "week");
    CHECK(tdx_kline_period_parse("month", &period, &error) == TDX_OK && period.id == 6 &&
              period.intraday == 0,
          "month");
    CHECK(tdx_kline_period_parse("5m", &period, &error) == TDX_OK && period.id == 0 &&
              period.intraday == 1,
          "5m");
    CHECK(tdx_kline_period_parse("15m", &period, &error) == TDX_OK && period.id == 1, "15m");
    CHECK(tdx_kline_period_parse("30m", &period, &error) == TDX_OK && period.id == 2, "30m");
    CHECK(tdx_kline_period_parse("60m", &period, &error) == TDX_OK && period.id == 3, "60m");
    CHECK(tdx_kline_period_parse("1h", &period, &error) == TDX_OK && period.id == 3 &&
              strcmp(period.name, "60m") == 0,
          "1h is an alias of 60m");
    /* time and 1m share period 7; the canonical name distinguishes them. */
    CHECK(tdx_kline_period_parse("time", &period, &error) == TDX_OK && period.id == 7 &&
              strcmp(period.name, "time") == 0,
          "time");
    CHECK(tdx_kline_period_parse("1m", &period, &error) == TDX_OK && period.id == 7 &&
              strcmp(period.name, "1m") == 0,
          "1m maps to the same id but keeps its own name");
    CHECK(tdx_kline_period_parse("DAILY", &period, &error) == TDX_OK && period.id == 4,
          "the name is case folded");
    CHECK(tdx_kline_period_parse(" day ", &period, &error) == TDX_OK && period.id == 4,
          "the name is trimmed");
    CHECK(tdx_kline_period_parse("tick", &period, &error) == TDX_ERR, "an unknown period fails");
    CHECK(tdx_kline_period_parse("", &period, &error) == TDX_ERR, "an empty period fails");
}

static void test_lc1_date(void) {
    tdx_error error;
    int date = 0;
    error.message[0] = '\0';
    /* year = word / 2048 + 2004, remainder = month * 100 + day.  So the word is
     * not a day count: 101 is 1 January and 309 is 9 March of the base year. */
    CHECK(tdx_kline_lc1_date(101, &date, &error) == TDX_OK && date == 20040101,
          "word 101 is 20040101, got %d (%s)", date, error.message);
    CHECK(tdx_kline_lc1_date(0x0135, &date, &error) == TDX_OK && date == 20040309,
          "word 0x0135 is 9 March of the base year, got %d", date);
    CHECK(tdx_kline_lc1_date(4096 + 101, &date, &error) == TDX_OK && date == 20060101,
          "two years later, got %d", date);
    /* 20260612 -> (2026-2004)*2048 + 612 = 45668. */
    CHECK(tdx_kline_lc1_date(45668, &date, &error) == TDX_OK && date == 20260612,
          "20260612, got %d (%s)", date, error.message);
    CHECK(tdx_kline_lc1_date(0xFFFF, &date, &error) == TDX_ERR,
          "0xFFFF decodes to month 1023 and must be refused");
}

static void test_block_index_code(void) {
    CHECK(tdx_kline_is_block_index_code("880301"), "880xxx is a block index");
    CHECK(tdx_kline_is_block_index_code("881001"), "881xxx is a block index");
    CHECK(!tdx_kline_is_block_index_code("000623"), "an ordinary code is not");
    CHECK(!tdx_kline_is_block_index_code("88030"), "five digits is not");
    CHECK(!tdx_kline_is_block_index_code("88030a"), "a non-digit is not");
    CHECK(!tdx_kline_is_block_index_code(NULL), "null is not");
}

/* --- requests --------------------------------------------------------- */

static void test_request(void) {
    tdx_buf request;
    tdx_error error;
    size_t index;
    int all_zero_tail = 1;
    error.message[0] = '\0';
    tdx_buf_init(&request);

    CHECK(tdx_kline_build_request(0, "000623", 4, 0, 6, &request, &error) == TDX_OK, "build: %s",
          error.message);
    CHECK(request.len == TDX_KLINE_REQUEST_SIZE, "the body is %zu bytes, expected %u",
          request.len, (unsigned)TDX_KLINE_REQUEST_SIZE);
    if (request.len == TDX_KLINE_REQUEST_SIZE) {
        CHECK(tdx_u16le(request.data) == 0, "market at +0");
        CHECK(memcmp(request.data + 2, "000623", 6) == 0, "the code sits at +2");
        CHECK(tdx_u16le(request.data + 8) == 4, "period id at +8");
        CHECK(tdx_u16le(request.data + 10) == TDX_KLINE_PERIOD_PARAMETER,
              "the period parameter at +10 is always 1");
        CHECK(tdx_u16le(request.data + 12) == 0, "start at +12");
        CHECK(tdx_u16le(request.data + 14) == 6, "count at +14");
        for (index = 16; index < request.len; ++index)
            if (request.data[index] != 0)
                all_zero_tail = 0;
        CHECK(all_zero_tail, "the 26 bytes after the count must be zero");
    }

    CHECK(tdx_kline_build_request(1, "000001", 7, 100, 800, &request, &error) == TDX_OK,
          "id 7 with a full page: %s", error.message);
    if (request.len == TDX_KLINE_REQUEST_SIZE) {
        CHECK(tdx_u16le(request.data) == 1, "market 1");
        CHECK(tdx_u16le(request.data + 8) == 7, "period 7");
        CHECK(tdx_u16le(request.data + 12) == 100, "start 100");
        CHECK(tdx_u16le(request.data + 14) == 800, "count 800");
    }

    /* A short code leaves the gap zero padded rather than shifting the fields. */
    CHECK(tdx_kline_build_request(0, "1A", 4, 0, 1, &request, &error) == TDX_OK,
          "a short code: %s", error.message);
    if (request.len == TDX_KLINE_REQUEST_SIZE) {
        CHECK(request.data[2] == '1' && request.data[3] == 'A' && request.data[4] == 0,
              "the code must be left aligned and zero padded");
        CHECK(tdx_u16le(request.data + 8) == 4, "the period field must not shift");
    }

    CHECK(tdx_kline_build_request(0, "000623", 4, 0, 0, &request, &error) == TDX_ERR,
          "a zero count must be refused");
    CHECK(tdx_kline_build_request(0, "000623", 4, 0, 801, &request, &error) == TDX_ERR,
          "a count above 800 must be refused");
    CHECK(tdx_kline_build_request(3, "000623", 4, 0, 6, &request, &error) == TDX_ERR,
          "market 3 must be refused");
    CHECK(tdx_kline_build_request(0, "0006237", 4, 0, 6, &request, &error) == TDX_ERR,
          "a seven-character code must be refused");
    CHECK(tdx_kline_build_request(0, "00062-", 4, 0, 6, &request, &error) == TDX_ERR,
          "a punctuation character must be refused");
    CHECK(tdx_kline_build_request(0, "000623", 12, 0, 6, &request, &error) == TDX_ERR,
          "period 12 is outside the known range");
    tdx_buf_free(&request);
}

/* --- replies ---------------------------------------------------------- */

static void test_parse_daily(void) {
    tdx_kline_page page;
    tdx_error error;
    error.message[0] = '\0';
    tdx_kline_page_init(&page);

    CHECK(tdx_kline_parse(daily_reply, sizeof(daily_reply), 4, 0, &page, &error) == TDX_OK,
          "daily parse: %s", error.message);
    CHECK(page.count == 6, "six bars, got %zu", page.count);
    if (page.count == 6) {
        const tdx_kline_bar *first = &page.bars[0];
        const tdx_kline_bar *last = &page.bars[5];
        CHECK(first->date == 20260914, "the first date %d", first->date);
        CHECK(first->hour == 15 && first->minute == 0, "a daily bar is stamped 15:00, got %02d:%02d",
              first->hour, first->minute);
        CHECK(first->open == 17.56, "open %.3f", first->open);
        CHECK(first->high == 17.68, "high %.3f", first->high);
        CHECK(first->low == 17.48, "low %.3f", first->low);
        CHECK(first->close == 17.58, "close %.3f", first->close);
        CHECK(first->volume == 6421189, "volume %lld", (long long)first->volume);
        CHECK(first->amount > 112760727.0 && first->amount < 112760729.0, "amount %.2f",
              first->amount);
        CHECK(!first->has_extras, "a stock bar carries no breadth fields");
        CHECK(last->date == 20260921, "the last date %d", last->date);
        CHECK(last->close == 17.75, "the last close %.3f", last->close);
        CHECK(last->volume == 8738903, "the last volume %lld", (long long)last->volume);
        /* Every bar must satisfy its own envelope. */
        {
            size_t index;
            for (index = 0; index < page.count; ++index) {
                const tdx_kline_bar *bar = &page.bars[index];
                CHECK(bar->high >= bar->low, "bar %zu high %.3f below low %.3f", index,
                      bar->high, bar->low);
                CHECK(bar->open <= bar->high && bar->open >= bar->low,
                      "bar %zu open %.3f outside [%.3f, %.3f]", index, bar->open, bar->low,
                      bar->high);
                CHECK(bar->close <= bar->high && bar->close >= bar->low,
                      "bar %zu close %.3f outside [%.3f, %.3f]", index, bar->close, bar->low,
                      bar->high);
            }
        }
    }
    tdx_kline_page_free(&page);
}

static void test_parse_minute(void) {
    tdx_kline_page page;
    tdx_error error;
    error.message[0] = '\0';
    tdx_kline_page_init(&page);

    CHECK(tdx_kline_parse(minute_reply, sizeof(minute_reply), 7, 0, &page, &error) == TDX_OK,
          "minute parse: %s", error.message);
    CHECK(page.count == 6, "six bars, got %zu", page.count);
    if (page.count == 6) {
        const tdx_kline_bar *first = &page.bars[0];
        CHECK(first->date == 20260921, "the intraday date comes from an LC1 word: %d",
              first->date);
        CHECK(first->hour == 14 && first->minute == 55, "the first bar is 14:55, got %02d:%02d",
              first->hour, first->minute);
        CHECK(first->open == 17.76 && first->close == 17.76, "open %.3f close %.3f",
              first->open, first->close);
        CHECK(first->high == 17.77 && first->low == 17.75, "high %.3f low %.3f", first->high,
              first->low);
        CHECK(first->volume == 47500, "volume %lld", (long long)first->volume);
        /* The fixture runs 14:55..15:00, so the last bar is the close. */
        CHECK(page.bars[5].hour == 15 && page.bars[5].minute == 0,
              "the last bar is 15:00, got %02d:%02d", page.bars[5].hour, page.bars[5].minute);
    }
    tdx_kline_page_free(&page);
}

static void test_parse_index(void) {
    tdx_kline_page page;
    tdx_error error;
    error.message[0] = '\0';
    tdx_kline_page_init(&page);

    CHECK(tdx_kline_parse(index_reply, sizeof(index_reply), 4, 1, &page, &error) == TDX_OK,
          "index parse: %s", error.message);
    CHECK(page.count == 4, "four bars, got %zu", page.count);
    if (page.count == 4) {
        CHECK(page.bars[0].date == 20260916, "the first date %d", page.bars[0].date);
        CHECK(page.bars[0].has_extras == 1, "index mode must read the breadth fields");
        CHECK(page.bars[0].extra_1 == 1650 && page.bars[0].extra_2 == 608,
              "breadth %u/%u", (unsigned)page.bars[0].extra_1,
              (unsigned)page.bars[0].extra_2);
        CHECK(page.bars[0].close > 3800.0 && page.bars[0].close < 4000.0,
              "an index close is a different scale, got %.2f", page.bars[0].close);
        CHECK(page.bars[2].extra_1 == 1756 && page.bars[2].extra_2 == 519, "breadth %u/%u",
              (unsigned)page.bars[2].extra_1, (unsigned)page.bars[2].extra_2);
    }
    tdx_kline_page_free(&page);

    /* The same index bytes without index mode must be rejected: the four breadth
     * bytes are then read as the next record's date, which is not a date.  That
     * is the check that keeps the two record shapes from being conflated. */
    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(index_reply, sizeof(index_reply), 4, 0, &page, &error) == TDX_ERR,
          "index bytes parsed as a stock series must be rejected");
    CHECK(strstr(error.message, "invalid daily") != NULL,
          "the mismatch surfaces as a bad date, got: %s", error.message);
    tdx_kline_page_free(&page);
}

static void test_parse_rejects(void) {
    tdx_kline_page page;
    tdx_error error;
    uint8_t body[64];
    error.message[0] = '\0';

    tdx_kline_page_init(&page);
    {
        static const uint8_t empty_page[2] = {0x00, 0x00};
        CHECK(tdx_kline_parse(empty_page, sizeof(empty_page), 4, 0, &page, &error) == TDX_OK,
              "a page with no bars is legal; the walk just stops");
    }
    tdx_kline_page_free(&page);

    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(daily_reply, 1, 4, 0, &page, &error) == TDX_ERR,
          "a one-byte body must be rejected");
    tdx_kline_page_free(&page);

    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(daily_reply, sizeof(daily_reply) - 3, 4, 0, &page, &error) == TDX_ERR,
          "a truncated final record must be rejected");
    tdx_kline_page_free(&page);

    /* A count that exceeds the 800 cap. */
    memset(body, 0, sizeof(body));
    body[0] = 0x21;
    body[1] = 0x03; /* 801 */
    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(body, sizeof(body), 4, 0, &page, &error) == TDX_ERR,
          "a count above 800 must be rejected");
    CHECK(strstr(error.message, "above the") != NULL, "the error must say why: %s",
          error.message);
    tdx_kline_page_free(&page);

    /* A count with no records behind it. */
    memset(body, 0, sizeof(body));
    body[0] = 0x02;
    body[1] = 0x00;
    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(body, 2, 4, 0, &page, &error) == TDX_ERR,
          "a count with no records must be rejected");
    tdx_kline_page_free(&page);

    /* An impossible daily date. */
    memset(body, 0, sizeof(body));
    body[0] = 0x01;
    body[1] = 0x00;
    body[2] = 0x00;
    body[3] = 0x00;
    body[4] = 0x00;
    body[5] = 0x00; /* date 0 */
    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(body, sizeof(body), 4, 0, &page, &error) == TDX_ERR,
          "date 0 must be rejected");
    CHECK(strstr(error.message, "invalid daily") != NULL, "the error must name the field: %s",
          error.message);
    tdx_kline_page_free(&page);

    /* A record that claims more bytes than the body holds. */
    tdx_kline_page_init(&page);
    CHECK(tdx_kline_parse(daily_reply, 8, 4, 0, &page, &error) == TDX_ERR,
          "a record with no price fields must be rejected");
    tdx_kline_page_free(&page);
}

/* --- sorting and rendering -------------------------------------------- */

static void test_sort(void) {
    tdx_kline_bar bars[4];
    memset(bars, 0, sizeof(bars));
    bars[0].date = 20260102;
    bars[0].hour = 15;
    bars[1].date = 20260101;
    bars[1].hour = 15;
    bars[2].date = 20260102;
    bars[2].hour = 9;
    bars[2].minute = 30;
    bars[3].date = 20260101;
    bars[3].hour = 9;
    bars[3].minute = 31;
    tdx_kline_sort(bars, 4);
    CHECK(bars[0].date == 20260101 && bars[0].hour == 9 && bars[0].minute == 31,
          "the earliest bar first, got %d %02d:%02d", bars[0].date, bars[0].hour,
          bars[0].minute);
    CHECK(bars[1].date == 20260101 && bars[1].hour == 15, "then the same day's close");
    CHECK(bars[2].date == 20260102 && bars[2].hour == 9, "then the next day's open");
    CHECK(bars[3].date == 20260102 && bars[3].hour == 15, "then the last bar");
}

/* Counts structural braces outside string literals. */
static int braces_balanced(const char *text) {
    int depth = 0;
    int in_string = 0;
    int escaped = 0;
    const char *cursor;
    for (cursor = text; *cursor; ++cursor) {
        if (in_string) {
            if (escaped)
                escaped = 0;
            else if (*cursor == '\\')
                escaped = 1;
            else if (*cursor == '"')
                in_string = 0;
            continue;
        }
        if (*cursor == '"')
            in_string = 1;
        else if (*cursor == '{')
            depth++;
        else if (*cursor == '}') {
            depth--;
            if (depth < 0)
                return 0;
        }
    }
    return !in_string && depth == 0;
}

static void test_json_rendering(void) {
    tdx_kline_series series;
    tdx_kline_page page;
    tdx_buf line;
    tdx_error error;
    char text[4096];
    size_t copy;

    error.message[0] = '\0';
    tdx_kline_series_init(&series);
    tdx_kline_page_init(&page);
    tdx_buf_init(&line);
    CHECK(tdx_kline_parse(daily_reply, sizeof(daily_reply), 4, 0, &page, &error) == TDX_OK,
          "parse: %s", error.message);
    series.bars = page.bars;
    series.count = page.count;
    series.capacity = page.capacity;
    series.pages = 1;
    series.page_size = 6;
    series.period_id = 4;
    series.index_mode = 0;
    series.reached_end = 1;

    CHECK(tdx_kline_format_bar(&line, &series.bars[0], 0, "000623", "day", &error) == TDX_OK,
          "bar render: %s", error.message);
    copy = line.len < sizeof(text) - 1 ? line.len : sizeof(text) - 1;
    memcpy(text, line.data, copy);
    text[copy] = '\0';
    CHECK(braces_balanced(text), "the bar object must be balanced: %s", text);
    CHECK(strstr(text, "\"type\":\"kline\"") != NULL, "the bar type");
    CHECK(strstr(text, "\"security_id\":\"SZ000623\"") != NULL, "the identity");
    CHECK(strstr(text, "\"period\":\"day\"") != NULL, "the period");
    CHECK(strstr(text, "\"date\":20260914") != NULL, "the date");
    CHECK(strstr(text, "\"time\":\"15:00\"") != NULL, "the time");
    CHECK(strstr(text, "\"open\":17.560") != NULL, "open");
    CHECK(strstr(text, "\"volume\":6421189") != NULL, "volume");
    CHECK(strstr(text, "\"extra_1\":null") != NULL, "a stock bar has null breadth");

    tdx_buf_clear(&line);
    CHECK(tdx_kline_format_summary(&line, &series, 0, "000623", "day", 0, "1.2.3.4:7709",
                                   &error) == TDX_OK,
          "summary render: %s", error.message);
    copy = line.len < sizeof(text) - 1 ? line.len : sizeof(text) - 1;
    memcpy(text, line.data, copy);
    text[copy] = '\0';
    CHECK(braces_balanced(text), "the summary must be balanced: %s", text);
    CHECK(text[line.len - 1] == '}', "the summary must end with '}'");
    CHECK(strstr(text, "\"type\":\"kline_summary\"") != NULL, "the summary type");
    CHECK(strstr(text, "\"bar_count\":6") != NULL, "the bar count");
    CHECK(strstr(text, "\"first_date\":20260914") != NULL, "the first date");
    CHECK(strstr(text, "\"last_date\":20260921") != NULL, "the last date");
    CHECK(strstr(text, "\"index_mode\":false") != NULL, "the index flag");
    CHECK(strstr(text, "\"high\":") != NULL && strstr(text, "\"low\":") != NULL,
          "a populated series reports its envelope: %s", text);

    /* An empty series must render nulls rather than invented zeros. */
    memset(&series, 0, sizeof(series));
    tdx_buf_clear(&line);
    CHECK(tdx_kline_format_summary(&line, &series, 0, "000623", "day", 0, NULL, &error) == TDX_OK,
          "empty summary render: %s", error.message);
    copy = line.len < sizeof(text) - 1 ? line.len : sizeof(text) - 1;
    memcpy(text, line.data, copy);
    text[copy] = '\0';
    CHECK(braces_balanced(text), "an empty summary must be balanced: %s", text);
    CHECK(strstr(text, "\"first_date\":null") != NULL, "missing dates render null");
    CHECK(strstr(text, "\"high\":null") != NULL, "an empty envelope renders null");
    CHECK(strstr(text, "\"endpoint\":null") != NULL, "a missing endpoint renders null");

    tdx_buf_free(&line);
    tdx_kline_page_free(&page);
}

int main(void) {
    test_periods();
    test_lc1_date();
    test_block_index_code();
    test_request();
    test_parse_daily();
    test_parse_minute();
    test_parse_index();
    test_parse_rejects();
    test_sort();
    test_json_rendering();

    if (failures) {
        printf("%d kline check(s) failed\n", failures);
        return 1;
    }
    printf("kline checks passed\n");
    return 0;
}
