#include "recon_contract_internal.hpp"

namespace tdx::recon_contract_detail {

const std::vector<ApiContractSpec>& api_contract_specs() {
    static const std::vector<ApiContractSpec> values{
        {"health", "原生服务健康状态", "/api/v1/health", false},
        {"features", "功能目录结构", "/api/v1/features", false},
        {"openapi", "OpenAPI 固定路径", "/api/v1/openapi.json", false},
        {"homepage", "Svelte 首页", "/", false},
        {"formula-workbench-route", "公式工作台嵌套路由与根相对资源", "/protocol/formulas", false},
        {"formula-icons", "TCalc DRAWICON 原生图标资源清单", "/api/v1/formulas/icons", false},
        {"formula-drawicon-sprite", "TCalc DRAWICON 透明 PNG 精灵图", "/api/v1/formulas/drawicon-strip.png", false},
        {"formula-coverage-render-fidelity-live", "已加载系统/用户公式数值与绘图语义分层审计", "/api/v1/formulas/coverage", true},
        {"invalid-market", "非法市场参数拒绝", "/api/v1/market/abnormal-details?view=explanation&market=xx&code=000001", false},
        {"formula-inline-post", "自定义通达信公式源码 POST 解释执行", "/api/v1/formulas/evaluate", true},
        {"formula-autofilter-trace-inline-post", "AUTOFILTER 只读接受/拒绝决策轨迹 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-custom-core-inline-post", "TCalc 自定义公式日期、柱状态与数学核心 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-sequence-statistics-inline-post", "TCalc 时序搜索与统计核心 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-rolling-variance-inline-post", "TCalc 滚动、条件与方差核心 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-benchmark-cumulative-inline-post", "TCalc 市场基准 BETA 与累加距离 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-calendar-filter-inline-post", "TCalc 日期到当前柱、日历转换、右对齐与交易信号过滤 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-directional-bars-inline-post", "TCalc 收盘方向段 DHIGH/DOPEN/DLOW/DCLOSE/DVOL 只读未来语义", "/api/v1/formulas/evaluate", true},
        {"formula-ziga-inline-post", "TCalc 绝对价格阈值 ZIGA 局部极值与尾段重绘 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-future-replay-inline-post", "未来函数 successive-prefix 历史重绘时间线 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-random-security-score-inline-post", "TCalc RAND 可复现种子与本地安全/亮点分 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-adjustment-flag-inline-post", "TCalc 复权模式 TQFLAG 自动变量及零参数调用 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-adjustment-qfq-get", "内置公式 GET 前复权 K 线与 0x000F 元数据透传", "/api/v1/formulas/evaluate?market=sz&code=000001&kind=stock&formula=MACD&period=day&pages=1&page_size=120&adjust=qfq&timeout_ms=30000", true},
        {"formula-security-string-inline-post", "TCalc 证券名称/代码字符串条件与涨跌方向 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-block-metadata-inline-post", "TCalc 本地板块归属、数量、名称与行业指数代码 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-block-code-name-inline-post", "TCalc 板块代码、成分数量及 HORCALC/INSORT/INSUM 横向统计 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-single-point-data-inline-post", "TCalc FINONE/JYONE/GPONEDAT 单点财务经营数据 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-type167-text-inline-post", "TCalc 一级研究行业、主营构成及本地组合板块文本 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-security-status-inline-post", "TCalc T+0/ST/退市/期货期权及交易日宿主状态 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-host-summary-inline-post", "TCalc 个股统计形态、主要指数及全市场汇总宿主数据 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-market-breadth-dyna-inline-post", "TCalc 大盘涨跌家数及现价/涨幅/量比/涨速快捷函数 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-security-relation-divfactor-inline-post", "TCalc 所属大盘、标的证券及送转复权因子 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-string-builders-inline-post", "TCalc GBK 字符串切片、格式化及序列/非序列拼接 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-drawicon-inline-post", "原生 DRAWICON 格号及上下对齐 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-drawcframe-inline-post", "DRAWCFRAME 原生适用范围、几何与 Alpha POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-price-annotations-inline-post", "DRAWTEXT/DRAWNUMBER 无框原生坐标、真值与格式化 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-drawnumber-dif-inline-post", "DRAWNUMBER_DIF 原生活动序列、STYLE=2 矩形与引线 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-series-sticks-inline-post", "COLORSTICK/VOLSTICK 原生几何、逐柱着色与配置 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-native-series-styles-inline-post", "STICK/LINESTICK/DOTLINE 及三种点线原生绘制语义", "/api/v1/formulas/evaluate", true},
        {"formula-mixed-render-order-inline-post", "混合公式源码语句与连续绘制顺序 POST 语义", "/api/v1/formulas/evaluate", true},
        {"formula-colorref-inline-post", "TCalc 命名色及 COLOR/RGBX 的 COLORREF 语义", "/api/v1/formulas/evaluate", true},
        {"formula-background-inline-post", "DRAWGBK_DIV 原生连续区域与 Alpha 语义", "/api/v1/formulas/evaluate", true},
        {"formula-explicit-context-post", "授权外部序列 POST 解释执行", "/api/v1/formulas/evaluate", true},
        {"formula-library-context-post", "内置公式与显式外部序列 POST 执行", "/api/v1/formulas/evaluate", true},
        {"formula-context-template-live", "公式私有/L2显式序列模板", "/api/v1/formulas/context-template?formula=ZJLX&stamp=2026-08-08%7C15%3A00", true},
        {"formula-context-template-kline-live", "按真实K线批量生成私有/L2序列空模板", "/api/v1/formulas/context-template?formula=ZJLX&market=sz&code=000001&period=day&pages=1&page_size=20", true},
        {"formula-context-import-post", "调用方授权捕获严格物化为显式上下文", "/api/v1/formulas/context-import", false},
        {"formula-context-import-partial-post", "调用方捕获缺点位有界诊断", "/api/v1/formulas/context-import", false},
        {"formula-limit-price-context-template-live", "涨跌停宿主raw标量模板跳过K线", "/api/v1/formulas/context-template?formula=B007&market=sz&code=000001&period=day&pages=1&page_size=800", true},
        {"formula-cross-market-audit-hk-live", "港股真实K线全库公式审计", "/api/v1/formulas/audit?market=31&code=00700&period=day&pages=1&page_size=120&with_context=1", true},
        {"formula-cross-market-futures-live", "期货持仓量公式解释执行", "/api/v1/formulas/evaluate?market=47&code=IFL9&formula=CCL&period=day&pages=1&page_size=60", true},
        {"formula-contract-multiplier-live", "期货合约乘数 type-105/23F5 公式解释执行", "/api/v1/formulas/evaluate", true},
        {"formula-kline-auxiliary-fields-live", "TCalc ZSTJJ/QHJSJ 共享 K 线辅助字段解释执行", "/api/v1/formulas/evaluate", true},
        {"formula-cross-market-option-live", "期权IVOLAT跨证券公式解释执行", "/api/v1/formulas/evaluate?market=7&code=HO8W03UX&formula=VOLATILITY&option_name=HO2608-C-2500&period=day&pages=1&page_size=60", true},
        {"formula-sqjz-sequence-live", "神奇九转连续数字绘图语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=SQJZ&period=day&pages=1&page_size=240&allow_future=1", true},
        {"formula-wavekx-partline-live", "波段K线条件色线方向语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=WAVEKX&period=day&pages=1&page_size=240&allow_future=1", true},
        {"formula-rgband-fill-live", "红绿带动态填充语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=RGBAND&period=day&pages=1&page_size=240", true},
        {"formula-tjcjl-stickline-live", "太极成交量原生柱宽与实心语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=TJCJL&period=day&pages=1&page_size=240", true},
        {"formula-ichimoku-stickline-live", "一目均衡小数EMPTY空心柱语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=ICHIMOKU&period=day&pages=1&page_size=240&allow_future=1", true},
        {"formula-cyx-drawline-live", "撑压线双锚点及右延直线语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=CYX&period=day&pages=1&page_size=240&allow_future=1", true},
        {"formula-fkx-candles-live", "反K线原生HIGH/OPEN/LOW/CLOSE蜡烛语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=FKX&period=day&pages=1&page_size=120", true},
        {"formula-slzt-linestick-live", "神龙在天青龙零轴柱体与指标线双组件语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=SLZT&period=day&pages=1&page_size=240", true},
        {"formula-cpbs-text-live", "操盘BS点价格文字标注语义", "/api/v1/formulas/evaluate?market=sz&code=000001&formula=CPBS&period=day&pages=1&page_size=240", true},
        {"formula-fscage-number-live", "笼子上下限价格数字标注与显式行情上下文语义", "/api/v1/formulas/evaluate", true},
        {"formula-cloud-calc-audit", "TBigData计算列与宿主字段覆盖审计", "/api/v1/formulas/cloud-calc", true},
        {"formula-cloud-calc-template", "TBigData可转债CFG最小输入模板", "/api/v1/formulas/cloud-calc/template?cfg=func_kzz_kzzsy101", true},
        {"formula-cloud-calc-live-post", "TBigData真实可转债行公开L1复算", "/api/v1/formulas/cloud-calc", true},
        {"formula-cloud-calc-batch-post", "TBigData两行榜单共享公开L1批量复算", "/api/v1/formulas/cloud-calc/batch", true},
        {"tpool-inline-evaluate-post", "TPool内联XML规则与流程投影", "/api/v1/pools/evaluate", true},
        {"formula-inline-scan-post", "自定义条件公式源码前复权 POST 扫描", "/api/v1/formulas/scan", true},
        {"formula-inline-backtest-post", "自定义专家公式源码前复权 POST 回测", "/api/v1/formulas/backtest", true},
        {"formula-strategy-scan-post", "多公式同 K 线前复权组合扫描", "/api/v1/formulas/strategy/scan", true},
        {"formula-strategy-backtest-post", "多公式前复权下一开盘组合回测与逐股归因", "/api/v1/formulas/strategy/backtest", true},
        {"empty-abnormal", "未上榜证券为空关系", "/api/v1/market/abnormal-details?view=explanation&market=sz&code=000000", true},
        {"empty-active-funds", "主动基金未持有证券为空关系", "/api/v1/market/active-funds?market=sz&code=000000", true},
        {"empty-institution-lhb", "机构龙虎未命中证券为空关系", "/api/v1/market/institution-lhb?period=week&market=sz&code=000000", true},
        {"empty-foreign-alerts", "外资预警未命中证券为空关系", "/api/v1/market/foreign-alerts?market=sz&code=000000", true},
        {"empty-fund-holdings", "不存在基金报告期持仓为空关系", "/api/v1/market/fund-analytics?view=reported-holding-securities&fund_code=999999&report_date=20251231", true},
        {"intraday-funds-live", "个股分时资金及缓存状态", "/api/v1/market/funds?market=sz&code=000001", true},
        {"stock-panorama-live", "个股个性数据全景及 JSN 健康", "/api/v1/market/panorama?view=capital-flow&market=sz&code=000001&limit=20", true},
        {"stock-institution-analysis-live", "个股机构持仓全景及 JSN 健康", "/api/v1/market/institution-analysis?view=all&market=sz&code=000001&limit=20", true},
        {"holder-cross-stock-live", "十大流通股东跨股票历史、单票明细及上游容错", "/api/v1/market/holder?holder_id=GD011907&variant_id=8000002&reference_code=000001&stock_code=000001&limit=5", true},
        {"generic-tqlex-live", "通用 TQLEX 配置查询与整批重试元数据", "/api/v1/tqlex/query?req_id=200626&source_file=123123.xml&page_size=100", true},
        {"generic-pbrpc-live", "通用 PBRPC 会话查询与整会话重试元数据", "/api/v1/pbrpc/query?req_id=200340&source_file=sszjtj.xml", true},
        {"institution-exclusive-funds-live", "基金独门明细、重复公司持仓与单位语义", "/api/v1/market/institution-analysis?view=exclusive-funds&limit=5", true},
        {"institution-national-team-live", "汇金证金持股比例与合计公式", "/api/v1/market/institution-analysis?view=national-team&limit=5", true},
        {"institution-notable-private-funds-live", "知名私募持仓、管理人关系与市值单位", "/api/v1/market/institution-analysis?view=notable-private-funds&limit=5000", true},
        {"institution-stake-building-live", "被举牌披露、增持字段与客户端区间收益公式", "/api/v1/market/institution-analysis?view=stake-building&limit=100", true},
        {"stock-connect-activity-live", "陆股通增仓历史快照语义", "/api/v1/market/stock-connect?view=activity&category=daily-increase&limit=5", true},
        {"empty-stock-connect-industry", "陆股通当前空分类表语义", "/api/v1/market/stock-connect?view=industry&category=northbound-industry&limit=5", true},
        {"intelligence-topics-live", "专题目录与动态明细键", "/api/v1/market/intelligence?view=topics&limit=100", true},
        {"intelligence-topic-detail-live", "专题时间线与安全纯文本正文", "/api/v1/market/intelligence?view=topic&topic_id=1039&limit=1000", true},
        {"intelligence-news-live", "新闻联播历史时间线", "/api/v1/market/intelligence?view=news&limit=5", true},
        {"market-anomalies-live", "大盘异动复盘及客户端公式", "/api/v1/market/intelligence?view=market-anomalies&limit=5", true},
        {"intelligence-event-detail-live", "事件动态成员与主表成员对账", "/api/v1/market/intelligence?view=event&event_id=20115&limit=100", true},
        {"intelligence-discredited-live", "失信被执行对象、公告日期与近一年次数", "/api/v1/market/intelligence?view=risks&category=discredited&limit=100", true},
        {"intelligence-value-attention-live", "价值关注分类、动态明细与主表成员对账", "/api/v1/market/intelligence?view=value-attention&category_id=3109&limit=100", true},
        {"margin-classifications-live", "行业两融快照与原始元单位", "/api/v1/market/margin?view=classifications&category=industry&limit=5", true},
        {"margin-classification-history-live", "两融分类历史亿元与千万元换算", "/api/v1/market/margin?view=classification-history&group_id=880868&limit=5", true},
        {"margin-etf-history-live", "ETF 两融主明细与图表资源", "/api/v1/market/margin?view=security&category=etf&market=sh&code=510900&limit=100", true},
        {"margin-transfer-live", "转融资/转融券历史及元/股原始单位", "/api/v1/market/margin?view=transfer&limit=5", true},
        {"stock-connect-chart-live", "单票持股主表与图表万元投影对账", "/api/v1/market/stock-connect?view=security&market=sz&code=000001&limit=100", true},
        {"stock-connect-industry-detail-live", "南向行业成分与亿元净流入历史", "/api/v1/market/stock-connect?view=industry-detail&group_id=70HK0201&limit=100", true},
        {"ownership-change-chart-live", "增减持公司数图表投影对账", "/api/v1/market/ownership?view=statistics&category=changes&limit=100", true},
        {"ownership-rankings-live", "股东减持比例聚合榜及单位语义", "/api/v1/market/ownership?view=rankings&category=decrease-ratio&limit=5", true},
        {"jsn-discovery-live", "JSN 基线、字段画像与类型化覆盖", "/api/v1/jsn/discovery?top=20", true},
        {"jsn-candidates-live", "JSN CFG 族/客户端页面限定的 refunit 动态候选安全队列", "/api/v1/jsn/candidates?family=gqzy&limit=5", true},
        {"shareholder-counts-live", "北证股东人数与股本关系", "/api/v1/market/ownership?view=shareholder-counts&category=bj&limit=5", true},
        {"empty-shareholder-counts-legacy", "合并前中小板股东人数为空关系", "/api/v1/market/ownership?view=shareholder-counts&category=sz-sme-legacy&limit=5", true},
        {"limit-review-current-live", "当日涨跌停非实时复盘", "/api/v1/market/limit-review?view=current&category=all&limit=3", true},
        {"limit-review-history-live", "市场涨跌停温度历史", "/api/v1/market/limit-review?view=history&limit=3", true},
        {"limit-review-daily-live", "指定日涨跌停成员", "/api/v1/market/limit-review?view=daily&category=all&date=20260731&limit=5", true},
        {"limit-review-security-live", "单票涨跌停原因历史", "/api/v1/market/limit-review?view=security&market=sz&code=000009&limit=20", true},
        {"session-turnover-a-live", "A 股开盘与盘后成交排行", "/api/v1/market/session-turnover?universe=a&sort=after-hours&limit=3", true},
        {"session-turnover-etf-live", "ETF 开盘与盘后成交排行", "/api/v1/market/session-turnover?universe=etf&sort=opening&limit=3", true},
        {"pending-convertible-bonds-live", "待发可转债方案进度与正股关联", "/api/v1/market/convertible-bonds?view=pending&limit=5", true},
        {"convertible-bond-subscriptions-live", "已发可转债申购、中签、上市及客户端转股公式", "/api/v1/market/convertible-bonds?view=subscriptions&limit=1000", true},
        {"exchangeable-bond-supplement-live", "可交换债独立收益表补齐核心条款", "/api/v1/market/convertible-bonds?view=listed&market=sh&code=132024&include_details=0", true},
        {"convertible-bond-pricing-live", "可转债收益表、公开 L1 与现金流复算", "/api/v1/market/convertible-bonds?view=pricing&market=sh&code=110076&sort=double-low&order=asc", true},
        {"bond-reference-aa-plus-live", "AA+债券条款、评级与付息序列", "/api/v1/market/bond-reference?group=rating&bucket=aa-plus&sort=maturity&order=asc&limit=5", true},
        {"bond-reference-universe-live", "全市场四万只债券条款、类型与付息序列", "/api/v1/market/bond-reference?group=category&bucket=all&sort=maturity&order=asc&limit=5", true},
        {"bond-reference-corporate-projections-live", "公司债全市场主表与沪深投影精确对账", "/api/v1/market/bond-reference?group=category&bucket=corporate&include_projections=1&sort=maturity&order=asc&limit=5", true},
        {"bond-reference-private-boundary-live", "私募债完整表、沪深投影与深市合并表边界", "/api/v1/market/bond-reference?group=category&bucket=private&include_projections=1&sort=code&order=asc&limit=1", true},
        {"bond-reference-government-live", "国债合并主表、原始规模边界与付息序列", "/api/v1/market/bond-reference?group=category&bucket=government&sort=maturity&order=asc&limit=5", true},
        {"bond-reference-policy-financial-live", "政策性金融债亿元规模与沪深投影对账", "/api/v1/market/bond-reference?group=category&bucket=policy-financial&sort=maturity&order=asc&limit=100", true},
        {"forecast-latest-live", "A 股全市场业绩预告主表与行业动态截面对账", "/api/v1/market/forecasts?view=latest&limit=5", true},
        {"private-placements-live", "定向增发六阶段生命周期、金额单位与来源覆盖", "/api/v1/market/futures-issuance?section=placements&placement_status=all&limit=5", true},
        {"rights-offerings-live", "配股实施、审议中与异常进度生命周期", "/api/v1/market/futures-issuance?section=rights&limit=1000", true},
        {"preferred-shares-live", "优先股发行规模、基础股票与股息条款", "/api/v1/market/futures-issuance?section=preferred-shares&limit=100", true},
        {"employee-share-plans-live", "员工持股计划购买、期限、批次与金额单位", "/api/v1/market/employees?view=share-plans&limit=5", true},
        {"hk-events-live", "港股分红、权益披露、沽空与上市申请单位语义", "/api/v1/market/hk-events?view=all&limit=20", true},
        {"hk-short-history-live", "港股日K历史沽空量与GGRL104逐日对账", "/api/v1/market/hk-short-history?market=31&code=00700&pages=1&page_size=60", true},
        {"special-situations-live", "吸收合并、B转H与主要指数市值管理预警", "/api/v1/market/special-situations?view=legacy&include_quotes=0&limit=500", true},
        {"corporate-transitions-live", "并购重组四阶段与新三板转板监管", "/api/v1/market/special-situations?view=all&include_quotes=0&limit=10000", true},
        {"exchange-funds-live", "ETF/LOF/封闭基金、货币套利与REITs发行", "/api/v1/market/exchange-funds?view=all&include_quotes=0&limit=10000", true},
        {"etf-share-ranking-live", "ETF份额、规模基准、跟踪指数与净流入原值", "/api/v1/market/exchange-funds?view=etf-share-ranking&include_quotes=0&limit=10000", true},
        {"curated-data-live", "客户端八类精选表、单位与历史边界", "/api/v1/market/curated-data?view=all&limit=5000", true},
        {"special-attention-live", "股权分散、潜在ST、摘星摘帽、立案调查与商誉风险", "/api/v1/market/special-attention?view=all&limit=5000", true},
        {"fund-statistics-live", "基金发行、分红、收益、规模、ETF申赎与上市统计", "/api/v1/market/fund-statistics?view=all&limit=5000", true},
        {"specialized-metrics-live", "银行、券商和保险专项经营指标与单位语义", "/api/v1/market/specialized-metrics?view=all&limit=5000", true},
        {"company-changes-live", "九类证券、公司、指数、股权与行业变更事实", "/api/v1/market/company-changes?view=all&limit=20000", true},
        {"financial-screen-live", "五板估值、成长、质量、机构与股息财务筛选", "/api/v1/market/financial-screen?view=all&sort=market-cap&order=desc&limit=10000", true},
        {"small-cap-growth-live", "小盘成长四期同比与三年复合增速", "/api/v1/market/financial-screen?dataset=small-cap-growth&view=all&sort=profit-cagr&order=desc&limit=100", true},
        {"equity-performance-live", "全A股多周期行情表现横截面", "/api/v1/market/equity-performance?sort=return-5d&order=desc&limit=10000", true},
        {"corporate-orders-live", "上市公司招投标、中标与重大合同", "/api/v1/market/corporate-orders?view=all&sort=date&order=desc&limit=10000", true},
        {"event-impact-live", "重大事件前后三地指数冲击", "/api/v1/market/event-impact?benchmark=all&sort=date&order=desc&limit=5000", true},
        {"global-performance-live", "主要指数与海外中资证券多周期表现", "/api/v1/market/global-performance?view=all&sort=return-5d&order=desc&limit=10000", true},
        {"ipo-guidance-live", "IPO上市辅导进度、机构、板块与地区", "/api/v1/market/calendar?view=ipo-guidance&limit=2000", true},
        {"ipo-review-live", "IPO审核状态、保荐人、招股书与拟发行结构", "/api/v1/market/calendar?view=ipo-review&limit=1000", true},
        {"ipo-subscriptions-live", "新股申购、发行结构与申购结果", "/api/v1/market/calendar?view=ipo-subscriptions&limit=100", true},
        {"ipo-subscription-details-live", "北交所新股日历申购、发行与上市详情", "/api/v1/market/calendar?view=ipo-subscription-details&limit=5000", true},
        {"us-ipo-live", "美股申请、排期、已上市与待上市阶段", "/api/v1/market/calendar?view=us-ipo&limit=5000", true},
        {"futures-calendar-live", "期货交易日历与交易所提示", "/api/v1/market/calendar?view=futures&limit=100", true},
        {"institution-social-security-summary-live", "社保流通股东持仓汇总", "/api/v1/market/institution-analysis?view=social-security-summary&limit=100", true},
        {"institution-development-bank-holdings-live", "国开系参股持仓披露", "/api/v1/market/institution-analysis?view=development-bank-holdings&limit=100", true},
        {"shareholder-signals-live", "牛散、机构增持、股东收缩与调研成长信号", "/api/v1/market/shareholder-signals?view=all&sort=signal&order=desc&limit=5000", true},
        {"notable-investor-holdings-live", "知名自然人目录与逐人持仓对账", "/api/v1/market/shareholder-signals?view=investor-directory&investor_id=GD012270&limit=5000", true},
        {"financial-insights-live", "十五类客户端特色财务筛选", "/api/v1/market/financial-insights?view=all&sort=signal&order=desc&limit=5000", true},
        {"gdr-live", "GDR与A股映射及溢价", "/api/v1/market/gdr?sort=date&order=desc&limit=1000", true},
        {"fund-calendar-live", "基金开放与分红事件日历", "/api/v1/market/fund-calendar?order=asc&limit=5000", true},
        {"recent-watch-live", "绩价背离、涉外经营与ST业绩预盈", "/api/v1/market/recent-watch?view=all&limit=5000", true},
        {"patent-statistics-live", "深沪京上市公司专利申请与授权统计", "/api/v1/market/patent-statistics?sort=cumulative-total&order=desc&limit=10000", true},
        {"overview-factors-live", "大盘分析十七项影响因素与源判断快照", "/api/v1/market/overview-factors?signal=all&limit=100", true},
        {"benchmark-analysis-live", "十三段牛熊周期、停复牌与次新股相对基准", "/api/v1/market/benchmark-analysis?view=stocks&stage=216&limit=5000", true},
        {"calendar-expanded-live", "重大事项、次新表现及板块资讯单票聚合", "/api/v1/market/calendar?view=all&market=sh&code=688783&limit=500", true},
        {"economic-indicators-catalog-live", "经济指标目录、环比同比与更新排序", "/api/v1/market/economic-indicators?view=catalog&sort=update-date&order=desc&limit=5", true},
        {"economic-indicator-detail-live", "阴极铜指标历史、关联股票与公开行情", "/api/v1/market/economic-indicators?view=indicator&indicator_id=M2800000005&limit=100&history_limit=5000", true},
        {"strategic-themes-catalog-live", "主题投资 26 类层级、598 个主题与成员关系", "/api/v1/market/strategic-themes?view=catalog&sort=name&order=asc&limit=700", true},
        {"strategic-theme-detail-live", "5G 概念成员、入选逻辑与主题明细资源", "/api/v1/market/strategic-themes?view=theme&theme_id=657&limit=5000", true},
        {"theme-library-catalog-live", "五类统一主题快照与最新主题目录", "/api/v1/market/theme-library?view=catalog&source=general&sort=created&order=desc&limit=1000", true},
        {"theme-library-detail-live", "实验猴主题成分、纳入原因与主题指数", "/api/v1/market/theme-library?view=theme&source=general&theme_id=3137&limit=100", true},
        {"thematic-opportunities-catalog-live", "一带一路行业区域机会组与成员关系", "/api/v1/market/thematic-opportunities?view=catalog&sort=name&order=asc&limit=100", true},
        {"thematic-opportunity-detail-live", "IGCC 技术逐股投资逻辑与参考价语义", "/api/v1/market/thematic-opportunities?view=group&group_id=hy57&limit=100", true},
        {"thematic-legacy-client-theme-live", "XNXS 页面声明冲突、快中子反应堆成员与逐股逻辑", "/api/v1/market/thematic-opportunities?view=group&group_id=299&limit=100", true},
        {"thematic-hype-completed-live", "近期已爆炒板块龙头与区间复盘", "/api/v1/market/thematic-opportunities?view=hype-completed&limit=100", true},
        {"thematic-hype-active-live", "当前爆炒股票与相对上证收益", "/api/v1/market/thematic-opportunities?view=hype-active&limit=100", true},
        {"block-rotation-live", "行业概念地区风格板块轮动", "/api/v1/market/block-rotation?category=all&period=1w&sort=anomalies&limit=5", true},
        {"limit-ladder-live", "研究行业与概念连板天梯", "/api/v1/market/limit-ladder?category=all&sort=total-height&limit=5", true},
        {"threshold-stocks-high-price-live", "百元股日期名单与入围跌出", "/api/v1/market/threshold-stocks?view=members&universe=high-price&sort=threshold-value&limit=5", true},
        {"threshold-stocks-mega-cap-live", "千亿市值日期名单与入围跌出", "/api/v1/market/threshold-stocks?view=members&universe=mega-cap&sort=threshold-value&limit=5", true},
        {"capital-strength-ranking-live", "五日 DDX 资金强势前百与单位语义", "/api/v1/market/capital-strength?view=ranking&period=5d&sort=ddx&limit=5", true},
        {"capital-strength-confluence-live", "五周期 DDX 榜单共振与来源对账", "/api/v1/market/capital-strength?view=confluence&min_periods=2&sort=period-count&limit=5", true},
        {"strong-stocks-intervals-live", "强势股生命周期主表与最新排序", "/api/v1/market/strong-stocks?view=intervals&sort=end-date&limit=5", true},
        {"strong-stocks-detail-live", "强势股区间逐日原因与市场温度", "/api/v1/market/strong-stocks?view=detail&interval_id=002827260729260806&limit=20", true},
        {"commodity-links-commodities-live", "商品行情与多周期价格变化", "/api/v1/market/commodity-links?view=commodities&sort=quote-date&limit=5", true},
        {"commodity-links-commodity-live", "商品关联股票与行业ETF", "/api/v1/market/commodity-links?view=commodity&commodity_id=X100102003", true},
        {"commodity-links-theme-live", "涨价题材长期关联股与历史驱动", "/api/v1/market/commodity-links?view=theme&theme_id=70", true},
        {"announcement-signals-selected-live", "公告精选、多空分类与 PDF 链接", "/api/v1/market/announcement-signals?view=selected&sort=date&limit=5", true},
        {"announcement-signals-risks-live", "风险提示公告及近期表现", "/api/v1/market/announcement-signals?view=risks&sort=date&limit=5", true},
        {"announcement-signals-history-live", "个股公告前后表现历史", "/api/v1/market/announcement-signals?view=history&market=sz&code=000921&sort=date&limit=10", true},
        {"reverse-repo-rates-live", "国债逆回购实时年化与净收益", "/api/v1/market/reverse-repo?view=rates&principal_yuan=100000&sort=net-rate&order=desc&limit=18", true},
        {"reverse-repo-calendar-live", "国债逆回购交收日历降级路径", "/api/v1/market/reverse-repo?view=rates&include_quotes=0&sort=term&order=asc&limit=18", true},
        {"exchange-supervision-current-live", "当前交易所监管期、公告与实时区间表现", "/api/v1/market/exchange-supervision?view=current&sort=end-date&order=desc&limit=20", true},
        {"exchange-supervision-history-live", "历史交易所监管期与起止价表现", "/api/v1/market/exchange-supervision?view=history&sort=end-date&order=desc&limit=20", true},
        {"tender-offers-live", "要约收购全市场事件、单位与进度覆盖", "/api/v1/market/tender-offers?sort=announcement-date&order=desc&limit=500", true},
        {"stock-tender-offers-live", "单票要约收购历史与筛选身份", "/api/v1/market/tender-offers?market=sh&code=600491&sort=announcement-date&order=desc&limit=20", true},
        {"active-lhb-ranking-live", "三周期活跃龙虎榜聚合排行与来源对账", "/api/v1/market/active-lhb?period=5d&sort=events&order=desc&limit=5&include_details=0", true},
        {"active-lhb-security-live", "单票半年活跃龙虎与逐次异动详情", "/api/v1/market/active-lhb?period=half-year&market=sh&code=603459&include_details=1&detail_limit=100", true},
        {"state-owned-groups-live", "国企改革整合预期分组与完整成员关系", "/api/v1/market/state-owned-reform?view=groups&dimension=integration&sort=count&order=desc&limit=5&include_quotes=0", true},
        {"state-owned-group-detail-live", "央企整合控制人、控股比例、逻辑与公开行情", "/api/v1/market/state-owned-reform?view=group&group_id=gl197&detail_limit=100", true},
        {"state-owned-restructuring-live", "国企重组预期资料、控制人和公开行情", "/api/v1/market/state-owned-reform?view=restructuring&sort=date&order=desc&limit=5", true},
        {"intelligence-highlights-live", "全市场安全亮点排行", "/api/v1/market/intelligence?view=highlights&sort=highlight-count&limit=5", true},
        {"stock-intelligence-highlight-live", "单票安全亮点关联", "/api/v1/market/intelligence?view=security&market=sh&code=600519&limit=20", true},
        {"stock-native-valuation-live", "个股四项原生估值及逆向公式", "/api/v1/market/stats?market=sz&code=000001&valuation=1&timeout_ms=30000", true},
        {"market-kline-30m-live", "30分钟历史K线、跨页时间升序、配置主站及续页元数据", "/api/v1/kline?market=sz&code=000001&period=30m&pages=2&page_size=80&date=all&timeout_ms=30000", true},
        {"market-auction-native-live", "原生集合竞价及配置主站元数据", "/api/v1/market/auction?market=sz&code=000001&limit=20&timeout_ms=30000", true},
        {"market-trades-native-live", "原生成交明细及配置主站元数据", "/api/v1/market/trades?market=sz&code=000001&date=20260807&page_size=2000&max_pages=10&timeout_ms=30000", true},
        {"market-ranking-native-live", "原生服务端排行及配置主站元数据", "/api/v1/market/ranking?sort=rise-speed&count=5&timeout_ms=30000", true},
        {"market-securities-native-live", "原生证券目录、完整分页及配置主站元数据", "/api/v1/market/securities?market=sz&category=a_share&limit=3&refresh=1&timeout_ms=30000", true},
        {"historical-securities-local", "本地历史证券兼容名称、当前目录对账及零网络边界", "/api/v1/market/historical-securities?presence=absent&sort=code&order=asc&limit=3", false},
        {"market-speed-live", "公开服务端涨速与五档快照", "/api/v1/market/speed?market=sz&code=000001&timeout_ms=30000", true},
        {"market-speed-etf-iopv-live", "公开行情核心 ETF IOPV", "/api/v1/market/speed?market=sh&code=510300&timeout_ms=30000", true},
        {"market-stream-live", "共享持久 L1 会话与 SSE 行情事件", "/api/v1/market/stream?market=sz&code=000001&max_events=1&wait_timeout_ms=30000", true},
        {"stock-research-live", "个股调研数据及 JSN 缓存状态", "/api/v1/market/research?market=sz&code=000001&include_text=0&detail_limit=5", true},
        {"stock-consensus-live", "个股一致预期及 JSN 缓存状态", "/api/v1/market/consensus?market=sz&code=000001&include_report_text=0&report_limit=5", true},
        {"consensus-stage-rankings-live", "一致预期年内低点涨幅及九榜来源", "/api/v1/market/consensus?category=year-low-rise&limit=5&include_report_text=0", true},
        {"stock-industry-profile-live", "个股行业画像及 JSN 缓存状态", "/api/v1/market/industry-profile?market=sz&code=000001&detail_limit=5", true},
        {"stock-ownership-live", "个股股东变动及 JSN 缓存状态", "/api/v1/market/ownership?view=changes&market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-repurchases-live", "个股回购数据及 JSN 缓存状态", "/api/v1/market/repurchases?view=plans&market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-institution-lhb-live", "个股机构龙虎及 JSN 缓存状态", "/api/v1/market/institution-lhb?period=week&market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-ratings-live", "个股行业评级及 JSN 缓存状态", "/api/v1/market/ratings?view=industries&market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-foreign-alerts-live", "个股外资预警及 JSN 缓存状态", "/api/v1/market/foreign-alerts?market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-unlocks-live", "个股限售解禁及 JSN 缓存状态", "/api/v1/market/unlocks?market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"recent-large-unlocks-live", "近期大比例解禁滚动窗口与比例语义", "/api/v1/market/unlocks?view=recent-large&limit=5000", true},
        {"unlock-monthly-pressure-live", "未来月度解禁规模、市值与占比压力", "/api/v1/market/unlocks?view=monthly-pressure&limit=100", true},
        {"stock-block-trades-live", "个股大宗交易及 JSN 缓存状态", "/api/v1/market/block-trades?view=trades&market=sz&code=000001&include_details=1&detail_limit=5", true},
        {"stock-lhb-live", "个股龙虎榜事件及 JSN 缓存状态", "/api/v1/market/lhb?market=sz&code=000001&include_details=1&limit=5", true},
        {"stock-roadshows-live", "个股路演及无 ReqId TQLEX KV 路由状态", "/api/v1/market/roadshows?market=sz&code=000001&limit=5", true},
        {"cloud-variants-fixed", "云配置语义变体类型化覆盖", "/api/v1/cloud/variants?gaps_only=1", true},
        {"report-cache-default", "基金报告期默认回退语义", "/api/v1/market/fund-analytics?view=reported-holding-securities&fund_code=000326", true},
        {"report-cache-explicit", "基金显式报告期缓存隔离", "", true},
    };
    return values;
}

}  // namespace tdx::recon_contract_detail
