/* tdx_panorama_views.c - the panorama view registry. GENERATED.
 *
 * Do not hand edit: produced by c/tools/generators/make_panorama_views.py from the reference's own
 * view table in native/src/market/panorama.cpp.  Ten views and 112 field mappings - a
 * transcription job whose mistakes would look like plausible column names.
 *
 * The labels are UTF-8 byte escapes so this file stays ASCII. */

#include "tdx_panorama.h"

const tdx_panorama_view tdx_panorama_views[] = {
    {"quality-rating",
     "\xe9\x87\x8f\xe5\x8c\x96\xe5\x90\xb8\xe5\xbc\x95\xe5\x8a\x9b\xe8\xaf\x84\xe7\xba\xa7",
     "list/func_aqfph101_1.jsn", "$SC", "$ZQDM",
     9, (const tdx_panorama_field[]){
         {"latest_date", "date"},
         {"latest_score", "zxfs"},
         {"previous_date", "date1"},
         {"previous_score", "scfs"},
         {"rating_change", "pj"},
         {"risk_type", "fxlx"},
         {"leader_count", "lds"},
         {"leader_type", "ldlx"},
         {"pe_ttm", "syl"},
     }},
    {"capital-flow",
     "\xe5\xa4\x9a\xe5\x91\xa8\xe6\x9c\x9f\xe8\xb5\x84\xe9\x87\x91\xe6\xb5\x81\xe5\x90\x91",
     "list/func_gx_zjlx101_1.jsn", "$SC", "$ZQDM",
     9, (const tdx_panorama_field[]){
         {"statistics_date", "date"},
         {"main_net_inflow_1d", "rzljlr1"},
         {"main_net_inflow_5d", "rzljlr5"},
         {"main_net_inflow_10d", "rzljlr10"},
         {"main_net_inflow_20d", "rzljlr20"},
         {"main_net_inflow_30d", "rzljlr30"},
         {"net_inflow_5d", "rjlr5"},
         {"net_inflow_10d", "rjlr10"},
         {"net_inflow_20d", "rjlr20"},
     }},
    {"risk-watch",
     "\xe8\xb4\xa8\xe6\x8a\xbc\xe5\x95\x86\xe8\xaa\x89\xe8\xa7\xa3\xe7\xa6\x81\xe9\xa3\x8e\xe9\x99\xa9",
     "list/func_gx_fxgz101_1.jsn", "$SC", "$ZQDM",
     13, (const tdx_panorama_field[]){
         {"pledged_shares_10k", "ljzy"},
         {"pledged_total_share_pct", "zzgb"},
         {"pledge_warning_price", "yjj"},
         {"pledge_warning_shares_10k", "yjgs"},
         {"pledge_closeout_price", "pcj"},
         {"pledge_closeout_shares_10k", "pcgs"},
         {"goodwill_current", "sy1"},
         {"goodwill_previous", "sy2"},
         {"goodwill_change", "syzj"},
         {"goodwill_net_asset_pct", "syzgd"},
         {"unlock_date", "jjrq"},
         {"unlock_shares", "jjsl"},
         {"unlock_total_share_pct", "jjgzb"},
     }},
    {"financials",
     "\xe8\xb4\xa2\xe6\x8a\xa5\xe4\xb8\x8e\xe4\xbc\xb0\xe5\x80\xbc\xe6\x91\x98\xe8\xa6\x81",
     "list/func_gx_cbsj101_1.jsn", "$SC", "$ZQDM",
     18, (const tdx_panorama_field[]){
         {"report_period", "BGQ"},
         {"market_value_100m", "SZ"},
         {"pe_ttm", "PE"},
         {"pb_mrq", "PB"},
         {"peg", "PS"},
         {"debt_ratio_pct", "ZCFZ"},
         {"profit_yoy_pct", "TB1"},
         {"revenue_yoy_pct", "TB2"},
         {"roe_pct", "ROE"},
         {"gross_margin_pct", "XSM"},
         {"rd_expense_ratio_pct", "fyzb1"},
         {"sales_expense_ratio_pct", "fyzb2"},
         {"management_expense_ratio_pct", "fyzb3"},
         {"finance_expense_ratio_pct", "fyzb4"},
         {"revenue_turnover_pct", "ZZL1"},
         {"asset_turnover_pct", "ZZL2"},
         {"institution_holding_float_pct", "JGCC"},
         {"dividend_year", "FHND"},
     }},
    {"earnings-forecast",
     "\xe4\xb8\x9a\xe7\xbb\xa9\xe9\xa2\x84\xe5\x91\x8a\xe4\xb8\x8e\xe9\xa2\x84\xe6\xb5\x8b\xe4\xbc\xb0\xe5\x80\xbc",
     "list/func_gx_cbyg101_1.jsn", "$SC", "$ZQDM",
     11, (const tdx_panorama_field[]){
         {"forecast_date", "ygdate"},
         {"report_period", "bgq"},
         {"forecast_type", "type"},
         {"net_profit_lower", "jlr1"},
         {"net_profit_upper", "jlr2"},
         {"net_profit_previous", "jlr3"},
         {"profit_yoy_lower_pct", "zj3"},
         {"profit_yoy_upper_pct", "zj4"},
         {"eps", "eps"},
         {"forecast_profit_lower", "x"},
         {"forecast_profit_upper", "y"},
     }},
    {"analyst-estimate",
     "\xe6\x9c\xba\xe6\x9e\x84\xe8\xaf\x84\xe7\xba\xa7\xe4\xb8\x8e\xe7\x9b\x88\xe5\x88\xa9\xe9\xa2\x84\xe6\xb5\x8b",
     "list/func_gx_fxspj101_1.jsn", "$SC", "$ZQDM",
     12, (const tdx_panorama_field[]){
         {"latest_date", "ZXRQ"},
         {"research_count_6m", "JGSL"},
         {"composite_rating", "ZHPJ"},
         {"pe", "PE"},
         {"forecast_eps_growth_pct", "YCEPS"},
         {"target_price", "MBJ"},
         {"report_period", "BGQ"},
         {"current_eps", "MGSY"},
         {"industry", "hy"},
         {"forecast_base_year", "TBGQ"},
         {"forecast_eps_t", "MGSY0"},
         {"forecast_eps_t1", "MGSY1"},
     }},
    {"distribution",
     "\xe9\xab\x98\xe9\x80\x81\xe8\xbd\xac\xe4\xb8\x8e\xe5\x88\x86\xe7\xba\xa2\xe9\x80\x81\xe9\x85\x8d",
     "list/func_gx_zfsp101_1.jsn", "$SC", "$ZQDM",
     14, (const tdx_panorama_field[]){
         {"capital_reserve_per_share", "zbgj"},
         {"undistributed_profit_per_share", "wfplr"},
         {"parent_profit", "jlr1"},
         {"parent_profit_yoy_pct", "jlr3"},
         {"announcement_date", "ggdate"},
         {"bonus_transfer_per_10", "szbl"},
         {"cash_dividend_per_10", "xjfh"},
         {"record_date", "djdate"},
         {"ex_dividend_date", "qxdate"},
         {"plan_stage", "fajd"},
         {"rights_announcement_date", "ggrq"},
         {"rights_code", "dm"},
         {"rights_ratio", "bl"},
         {"rights_start_date", "qsjkr"},
     }},
    {"lhb-overview",
     "\xe9\xbe\x99\xe8\x99\x8e\xe6\xa6\x9c\xe6\x88\x90\xe4\xba\xa4\xe4\xb8\x8e\xe5\xb8\xad\xe4\xbd\x8d\xe6\xa6\x82\xe8\xa7\x88",
     "list/func_gx_lhbd101_1.jsn", "$SC1", "$ZQDM1",
     9, (const tdx_panorama_field[]){
         {"event_id", "$ZQDM"},
         {"event_date", "date"},
         {"buy_turnover_pct", "bzb"},
         {"sell_turnover_pct", "szb"},
         {"net_buy", "jmr"},
         {"buy_total", "zmr"},
         {"sell_total", "zmc"},
         {"stock_connect_seats", "sl1"},
         {"institution_seats", "sl2"},
     }},
    {"margin-overview",
     "\xe8\x9e\x8d\xe8\xb5\x84\xe8\x9e\x8d\xe5\x88\xb8\xe6\xa6\x82\xe8\xa7\x88",
     "list/func_gx_rzrq101_1.jsn", "$SC", "$ZQDM",
     9, (const tdx_panorama_field[]){
         {"statistics_date", "ygdate"},
         {"float_market_value", "J_LTSZ"},
         {"float_shares", "J_LTGB"},
         {"financing_balance", "rzye"},
         {"financing_net_buy", "drjme"},
         {"financing_market_value_pct", "rzzltsz"},
         {"short_balance_shares", "rqyl"},
         {"short_net_sell_shares", "drjml"},
         {"short_float_share_pct", "zqzltgf"},
     }},
    {"ownership-change",
     "\xe8\x82\xa1\xe4\xb8\x9c\xe5\xa2\x9e\xe5\x87\x8f\xe6\x8c\x81\xe5\x8c\xba\xe9\x97\xb4",
     "list/func_gx_zcjc101_1.jsn", "$SC", "$ZQDM",
     8, (const tdx_panorama_field[]){
         {"increase_value_10k", "zcsz"},
         {"decrease_value_10k", "jcsz"},
         {"net_change_value_10k", "jzcsz"},
         {"increase_price_min", "price1"},
         {"increase_price_max", "price2"},
         {"decrease_price_min", "price3"},
         {"decrease_price_max", "price4"},
         {"start_date", "date1"},
     }},
};

const size_t tdx_panorama_view_count = sizeof(tdx_panorama_views) / sizeof(tdx_panorama_views[0]);

/* The counts the test asserts, so a table that quietly shrank fails loudly. */
#define TDX_PANORAMA_VIEWS_EXPECTED 10
#define TDX_PANORAMA_FIELDS_EXPECTED 112
