"""Generate c/tests/professional_finance_fixtures.h.

The real package is 5.7 MB compressed and 13 MB uncompressed, so it cannot be embedded.
The archives are built independently of the C reader, then checked by Python's zipfile.
ZIP metadata and fixed-Huffman/LZ77 encoding are explicit so Python/zlib versions cannot
change generated bytes. zlib is used only to check decompression and compute CRC-32.

Four archives, chosen for the branches that matter:

  stored    method 0, so the copy path is exercised
  deflate   method 8, so the inflate path is exercised
  bad_crc   the deflate archive with its CRC field corrupted, so the CRC check is shown
            to actually reject rather than merely exist
  no_eocd   a valid archive with its end record removed, so the reader refuses it

The finance member inside each is a two-record table built here, with values chosen so a
wrong field offset shows up as a wrong number rather than as a plausible one.

    python c/tools/generators/make_professional_finance_fixtures.py
"""
import io
import os
import struct
import zlib
import zipfile

from generator_support import INPUT, OUTPUT
HERE = str(INPUT)
ROOT = str(OUTPUT)
TARGET = str(OUTPUT / "c/tests/professional_finance_fixtures.h")
MEMBER_NAME = 'gpcw20260630.dat'

FIELD_COUNT = 200
DATA_SIZE = FIELD_COUNT * 4
RECORDS = [('000001', [float(index) for index in range(FIELD_COUNT)]),
           ('600519', [float(index) * 2.0 for index in range(FIELD_COUNT)])]


def member_bytes():
    """The finance table: 20-byte header, 11-byte index entries, then the float blocks."""
    index_size = 11
    # H I H H H I I = 20 bytes: the reference reads through the data size at 12 and
    # treats the header as 20, so the last four bytes are unread padding here too.
    header = struct.pack('<HIHHHII', 1, 20260630, len(RECORDS), 0, index_size, DATA_SIZE,
                         0)
    assert len(header) == 20, len(header)
    index_offset = 20
    data_start = index_offset + len(RECORDS) * index_size
    index = b''
    data = b''
    for position, (code, values) in enumerate(RECORDS):
        offset = data_start + position * DATA_SIZE
        index += code.encode('ascii') + b'\x00' + struct.pack('<I', offset)
        data += struct.pack('<%df' % FIELD_COUNT, *values)
    return header + index + data, data_start


def fixed_deflate(data):
    """One RFC 1951 fixed-Huffman block, with deterministic greedy LZ77 matches.

    Prefer the nearest match on equal lengths. This tiny fixture encoder is not
    a general compression library; zipfile and zlib independently validate it.
    """
    output = bytearray()
    pending = 0
    pending_bits = 0

    def bits(value, count):
        nonlocal pending, pending_bits
        pending |= value << pending_bits
        pending_bits += count
        while pending_bits >= 8:
            output.append(pending & 255)
            pending >>= 8
            pending_bits -= 8

    def huffman(value, count):
        reversed_code = 0
        for _ in range(count):
            reversed_code = (reversed_code << 1) | (value & 1)
            value >>= 1
        bits(reversed_code, count)

    def literal(symbol):
        if symbol <= 143:
            huffman(0x30 + symbol, 8)
        elif symbol <= 255:
            huffman(0x190 + symbol - 144, 9)
        elif symbol <= 279:
            huffman(symbol - 256, 7)
        else:
            huffman(0xc0 + symbol - 280, 8)

    length_bases = (3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27,
                    31, 35, 43, 51, 59, 67, 83, 99, 115, 131, 163, 195, 227, 258)
    length_bits = (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                   2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0)
    distance_bases = (1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129,
                      193, 257, 385, 513, 769, 1025, 1537, 2049, 3073, 4097,
                      6145, 8193, 12289, 16385, 24577)
    distance_bits = (0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6,
                     6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13)
    bits(3, 3)  # BFINAL=1, BTYPE=01 (fixed Huffman), least-significant bit first.
    position = 0
    while position < len(data):
        best_length = 0
        best_distance = 0
        maximum = min(258, len(data) - position)
        for previous in range(position - 1, max(-1, position - 32769), -1):
            length = 0
            while length < maximum and data[previous + length] == data[position + length]:
                length += 1
            if length > best_length:
                best_length, best_distance = length, position - previous
                if length == maximum:
                    break
        if best_length < 3:
            literal(data[position])
            position += 1
            continue
        length_code = max(i for i, base in enumerate(length_bases) if base <= best_length)
        literal(257 + length_code)
        bits(best_length - length_bases[length_code], length_bits[length_code])
        distance_code = max(i for i, base in enumerate(distance_bases) if base <= best_distance)
        huffman(distance_code, 5)
        bits(best_distance - distance_bases[distance_code], distance_bits[distance_code])
        position += best_length
    literal(256)  # End of block.
    if pending_bits:
        output.append(pending & 255)
    encoded = bytes(output)
    assert zlib.decompress(encoded, -15) == data
    return encoded


def build(method):
    payload, data_start = member_bytes()
    compressed = payload if method == zipfile.ZIP_STORED else fixed_deflate(payload)
    if method == zipfile.ZIP_DEFLATED:
        assert len(compressed) < len(payload), 'method 8 must exercise actual compression'
    info = zipfile.ZipInfo(MEMBER_NAME, date_time=(2000, 1, 1, 0, 0, 0))
    info.compress_type = method
    info.create_system = 0
    info.create_version = info.extract_version = 20
    info.reserved = info.flag_bits = info.volume = info.internal_attr = 0
    info.external_attr = 0o600 << 16
    info.extra = info.comment = b''
    info.header_offset = 0
    info.CRC = zlib.crc32(payload) & 0xffffffff
    info.file_size, info.compress_size = len(payload), len(compressed)
    name = info.filename.encode('ascii')
    dos_time, dos_date = 0, ((2000 - 1980) << 9) | (1 << 5) | 1
    # Explicit single-member ZIP records: no writer defaults or compressor heuristics.
    local = struct.pack('<IHHHHHIIIHH', 0x04034b50, info.extract_version,
                        info.flag_bits, method, dos_time, dos_date, info.CRC,
                        info.compress_size, info.file_size, len(name), 0) + name
    central = struct.pack('<IHHHHHHIIIHHHHHII', 0x02014b50,
                          info.create_version | (info.create_system << 8),
                          info.extract_version, info.flag_bits, method, dos_time,
                          dos_date, info.CRC, info.compress_size, info.file_size,
                          len(name), 0, 0, info.volume, info.internal_attr,
                          info.external_attr, info.header_offset) + name
    end = struct.pack('<IHHHHIIH', 0x06054b50, 0, 0, 1, 1, len(central),
                      len(local) + len(compressed), 0)
    result = local + compressed + central + end
    with zipfile.ZipFile(io.BytesIO(result)) as archive:
        assert archive.namelist() == [MEMBER_NAME]
        parsed = archive.getinfo(MEMBER_NAME)
        for field in ('filename', 'date_time', 'compress_type', 'create_system',
                      'create_version', 'extract_version', 'reserved', 'flag_bits',
                      'volume', 'internal_attr', 'external_attr', 'extra', 'comment',
                      'header_offset', 'CRC', 'file_size', 'compress_size'):
            assert getattr(parsed, field) == getattr(info, field), field
        assert archive.read(MEMBER_NAME) == payload
        assert archive.testzip() is None
    return result, payload, data_start


def c_literals(data, per_line=16):
    lines = []
    for index in range(0, len(data), per_line):
        chunk = data[index:index + per_line]
        lines.append('    ' + ', '.join('0x%02x' % byte for byte in chunk) + ',')
    return lines


stored, payload, data_start = build(zipfile.ZIP_STORED)
deflated, _, _ = build(zipfile.ZIP_DEFLATED)

# The deflate archive with its stored CRC broken: the central directory's CRC field is
# the first of the two, and both are checked, so either would do.
bad_crc = bytearray(deflated)
position = bad_crc.find(b'PK\x01\x02')
assert position >= 0
bad_crc[position + 16] ^= 0xff

# A valid archive with its end record removed.
no_eocd = deflated[:-22]

for broken in (bytes(bad_crc), no_eocd):
    try:
        with zipfile.ZipFile(io.BytesIO(broken)) as archive:
            archive.read(MEMBER_NAME)
    except zipfile.BadZipFile:
        pass
    else:
        raise AssertionError('independent ZIP reader accepted a broken archive')

out = [
    '/* professional_finance_fixtures.h - ZIP archives built by Python, GENERATED.',
    ' * Do not hand edit.',
    ' *',
    ' * Produced by c/tools/generators/make_professional_finance_fixtures.py with explicit ZIP',
    ' * metadata and deterministic fixed-Huffman/LZ77 DEFLATE. Python zipfile and zlib',
    ' * independently verify metadata, contents and rejection cases before C reads them.',
    ' *',
    ' * Each holds one member, %s, holding a two-record finance table: header, index and' % MEMBER_NAME,
    ' * %d floats per record.  The values are index and index times two, so a wrong field' % FIELD_COUNT,
    ' * offset shows up as a wrong number rather than as a plausible one.',
    ' *',
    ' * The real package is 5.7 MB compressed and 13 MB uncompressed and cannot be embedded;',
    ' * its measured facts are in output/professional_finance_evidence.txt. */',
    '#ifndef TDX_TEST_PROFESSIONAL_FINANCE_FIXTURES_H',
    '#define TDX_TEST_PROFESSIONAL_FINANCE_FIXTURES_H',
    '',
    '#define PROFINANCE_MEMBER_NAME "%s"' % MEMBER_NAME,
    '#define PROFINANCE_FIXTURE_RECORDS %d' % len(RECORDS),
    '#define PROFINANCE_FIXTURE_FIELDS %d' % FIELD_COUNT,
    '#define PROFINANCE_FIXTURE_DATA_SIZE %d' % DATA_SIZE,
    '#define PROFINANCE_FIXTURE_DATA_START %d' % data_start,
    '',
]
for name, data in [('stored', stored), ('deflate', deflated), ('bad_crc', bytes(bad_crc)),
                   ('no_eocd', no_eocd)]:
    out.append('/* %s archive, %d bytes. */' % (name, len(data)))
    out.append('static const unsigned char profinance_%s_zip[] = {' % name)
    out.extend(c_literals(data))
    out.append('};')
    out.append('#define PROFINANCE_%s_BYTES %d' % (name.upper(), len(data)))
    out.append('')
out.append('#endif /* TDX_TEST_PROFESSIONAL_FINANCE_FIXTURES_H */')
open(TARGET, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')

print('stored %d bytes, deflate %d bytes, bad_crc %d, no_eocd %d' % (
    len(stored), len(deflated), len(bad_crc), len(no_eocd)))
print('member %d bytes, data starts at %d, records %s' % (len(payload), data_start,
                                                          [code for code, _ in RECORDS]))
print('member crc %08x' % (zlib.crc32(payload) & 0xffffffff))
print('wrote', os.path.normpath(TARGET))
